/**
 * Five deep end-to-end user journeys — precise click paths mapped to persona fixtures.
 * Each scenario documents what the user expects to accomplish at every step.
 */

import type { UserFlowScenario } from "./userFlowSimulator";

/** Canonical deep scenarios — run all via scripts/deepUserFlowSimulation.ts */
export const DEEP_USER_FLOW_SCENARIOS: UserFlowScenario[] = [
  {
    id: "deep_p01_maya_vertical_jump",
    label: "P01 Maya — Home → Sport one day → basketball + vertical jump → build → review → execute",
    personaId: "P01",
    flow: "sport_day",
    testPriority: "P0",
    userStory:
      "In-season basketball player opens Sport-Focused one-day flow, picks basketball + vertical jump, lower body 45 min, builds workout, reviews blocks, starts training.",
    expectedUserOutcome:
      "Athletic lower-body session with jump/plyo transfer — not bodybuilding filler or Zone 2 steady cardio.",
    steps: [
      {
        id: "home",
        screen: "Home (/)",
        description: "User lands on home — sees Goal-Oriented and Sport-Focused cards",
        action: "assert_on_screen",
        expectRoute: "/",
      },
      {
        id: "tap_sport_one_day",
        screen: "Home",
        description: "User taps Sport-Focused Training → One day",
        action: "tap_home_card",
        homeCard: "sport_day",
        expectRoute: "/sport-mode?scope=day",
        expectPhase: "setup",
        userExpectation: "Sport setup form opens in day scope (not week)",
      },
      {
        id: "pick_basketball",
        screen: "Sport setup",
        description: "User searches sport list and taps Basketball chip",
        action: "tap_sport",
        sportSlug: "basketball",
        userExpectation: "Basketball appears in ranked sport slot 1",
      },
      {
        id: "pick_vertical_jump",
        screen: "Sport setup",
        description: "User taps Vertical Jump sub-focus under basketball",
        action: "toggle_subfocus",
        sportSlug: "basketball",
        subFocusSlug: "vertical_jump",
        userExpectation: "Sub-focus chip selected (max 3 per sport)",
      },
      {
        id: "pick_lower_body",
        screen: "Sport setup — one day options",
        description: "User taps Lower body bias chip",
        action: "tap_body_bias",
        bodyBias: "lower",
        userExpectation: "One-day body region set to lower",
      },
      {
        id: "pick_duration_45",
        screen: "Sport setup — one day options",
        description: "User taps 45 min duration chip",
        action: "tap_duration_chip",
        durationMinutes: 45,
        userExpectation: "Session length 45 min (matches DURATIONS UI)",
      },
      {
        id: "pick_energy_medium",
        screen: "Sport setup",
        description: "User sets intensity to Medium (Fresh/Fatigued/Medium row)",
        action: "tap_intensity",
        intensityLevel: "Medium",
        userExpectation: "Energy maps to medium for generation",
      },
      {
        id: "assert_build_enabled",
        screen: "Sport setup",
        description: "Build workout CTA enabled after sport + sub-focus selected",
        action: "assert_cta_enabled",
        cta: "build_workout",
        userExpectation: "User can proceed — not blocked by missing sport",
      },
      {
        id: "tap_build",
        screen: "Sport setup",
        description: "User taps Build workout — loading screen then recommendation",
        action: "tap_build_workout",
        expectRoute: "/sport-mode/recommendation",
        expectPhase: "review",
        userExpectation: "Generated workout visible with blocks; user can swap exercises",
      },
      {
        id: "assert_intent_transfer",
        screen: "Sport recommendation",
        description: "Generation inputs reflect UI selections (basketball + vertical_jump)",
        action: "assert_flow_intent_parity",
        userExpectation: "sportGoalContext matches what user configured in form",
      },
      {
        id: "tap_start",
        screen: "Sport recommendation",
        description: "User taps Start workout → Execute screen",
        action: "tap_start_workout",
        expectRoute: "/manual/execute",
        expectPhase: "train",
        userExpectation: "User can log sets — session is actionable",
      },
    ],
  },
  {
    id: "deep_p02_morgan_multi_sport",
    label: "P02 Morgan — Two sports, sub-focus blend, 60/40 split → generate",
    personaId: "P02",
    flow: "sport_day",
    testPriority: "P0",
    userStory:
      "Multi-sport athlete selects basketball + soccer, multiple sub-focuses, adjusts sport split slider, builds one-day session.",
    expectedUserOutcome:
      "Both sports influence exercise selection; COD/sprint/jump patterns; no single-sport drowning.",
    steps: [
      { id: "home", screen: "Home", description: "Open home", action: "assert_on_screen", expectRoute: "/" },
      {
        id: "sport_day",
        screen: "Home",
        description: "Sport-Focused → One day",
        action: "tap_home_card",
        homeCard: "sport_day",
        expectRoute: "/sport-mode?scope=day",
      },
      {
        id: "sport_basketball",
        screen: "Sport setup",
        description: "Add basketball as sport 1",
        action: "tap_sport",
        sportSlug: "basketball",
      },
      {
        id: "sport_soccer",
        screen: "Sport setup",
        description: "Add soccer as sport 2",
        action: "tap_sport",
        sportSlug: "soccer",
        sportSlot: 1,
      },
      {
        id: "sub_vj",
        screen: "Sport setup",
        description: "Basketball → vertical jump",
        action: "toggle_subfocus",
        sportSlug: "basketball",
        subFocusSlug: "vertical_jump",
      },
      {
        id: "sub_cod",
        screen: "Sport setup",
        description: "Basketball → change of direction",
        action: "toggle_subfocus",
        sportSlug: "basketball",
        subFocusSlug: "change_of_direction",
      },
      {
        id: "sub_speed",
        screen: "Sport setup",
        description: "Soccer → speed",
        action: "toggle_subfocus",
        sportSlug: "soccer",
        subFocusSlug: "speed",
      },
      {
        id: "sport_split",
        screen: "Sport setup — advanced",
        description: "User sets 60/40 sport focus split (basketball primary)",
        action: "set_sport_split",
        sportFocusPct: [60, 40],
      },
      {
        id: "body_lower",
        screen: "Sport setup",
        description: "Lower body bias",
        action: "tap_body_bias",
        bodyBias: "lower",
      },
      {
        id: "build",
        screen: "Sport setup",
        description: "Build workout",
        action: "tap_build_workout",
        expectRoute: "/sport-mode/recommendation",
        expectPhase: "review",
      },
      {
        id: "intent_parity",
        screen: "Recommendation",
        description: "Both sports + sub-focuses in generation context",
        action: "assert_flow_intent_parity",
      },
    ],
  },
  {
    id: "deep_p06_casey_hypertrophy_goal",
    label: "P06 Casey — Goal one day → hypertrophy + glutes/legs → build → review",
    personaId: "P06",
    flow: "goal_day",
    testPriority: "P1",
    userStory:
      "User wants muscle in glutes/legs without sport mode — Goal-Oriented one day with sub-focus chips.",
    expectedUserOutcome:
      "Hypertrophy 8–15 rep main work (median ≥10), lower-body honored, practical session structure.",
    steps: [
      { id: "home", screen: "Home", description: "Home screen", action: "assert_on_screen", expectRoute: "/" },
      {
        id: "goal_day",
        screen: "Home",
        description: "Goal-Oriented Training → One day",
        action: "tap_home_card",
        homeCard: "goal_day",
        expectRoute: "/manual/preferences",
        expectPhase: "setup",
      },
      {
        id: "goal_hypertrophy",
        screen: "Goal preferences",
        description: "User selects Build Muscle (Hypertrophy) as primary goal",
        action: "tap_primary_goal",
        goalLabel: "Build Muscle (Hypertrophy)",
      },
      {
        id: "sub_glutes",
        screen: "Goal preferences",
        description: "User toggles Glutes sub-focus",
        action: "toggle_goal_subfocus",
        goalLabel: "Build Muscle (Hypertrophy)",
        subFocusLabel: "Glutes",
      },
      {
        id: "sub_legs",
        screen: "Goal preferences",
        description: "User toggles Legs sub-focus",
        action: "toggle_goal_subfocus",
        goalLabel: "Build Muscle (Hypertrophy)",
        subFocusLabel: "Legs",
      },
      {
        id: "body_lower",
        screen: "Goal preferences",
        description: "User taps Lower body focus",
        action: "set_manual_preferences",
        manualPatch: { targetBody: "Lower" },
      },
      {
        id: "duration_45",
        screen: "Goal preferences",
        description: "User selects 45 min",
        action: "tap_duration_chip",
        durationMinutes: 45,
      },
      {
        id: "energy_medium",
        screen: "Goal preferences",
        description: "User selects Medium energy",
        action: "set_manual_preferences",
        manualPatch: { energyLevel: "medium" },
      },
      {
        id: "build",
        screen: "Goal preferences",
        description: "User taps Build workout",
        action: "tap_build_workout",
        expectRoute: "/manual/workout",
        expectPhase: "review",
      },
      {
        id: "intent_parity",
        screen: "Workout review",
        description: "Goals/sub-focus/body match fixture",
        action: "assert_flow_intent_parity",
      },
    ],
  },
  {
    id: "deep_p07_alex_hotel_gym",
    label: "P07 Alex — Profiles → Hotel gym → sport RSA → build with equipment constraint",
    personaId: "P07",
    flow: "sport_day",
    testPriority: "P0",
    userStory:
      "Traveling athlete switches gym profile to hotel, then builds soccer repeat-sprint session from limited equipment.",
    expectedUserOutcome:
      "Zero barbell/rack/cable exercises; ≥5 exercises with DB/band/bodyweight substitutions.",
    steps: [
      { id: "home", screen: "Home", description: "Home", action: "assert_on_screen", expectRoute: "/" },
      {
        id: "open_profiles",
        screen: "Home / Profiles",
        description: "User opens Profiles tab and selects Hotel Gym template",
        action: "switch_gym_template",
        gymTemplate: "hotel_gym",
        userExpectation: "Active gym profile uses hotel equipment list only",
      },
      {
        id: "sport_day",
        screen: "Home",
        description: "Sport-Focused → One day",
        action: "tap_home_card",
        homeCard: "sport_day",
        expectRoute: "/sport-mode?scope=day",
      },
      {
        id: "sport_soccer",
        screen: "Sport setup",
        description: "Select soccer",
        action: "tap_sport",
        sportSlug: "soccer",
      },
      {
        id: "sub_speed",
        screen: "Sport setup",
        description: "Select speed (UI label for repeat-sprint intent)",
        action: "toggle_subfocus",
        sportSlug: "soccer",
        subFocusSlug: "speed",
      },
      {
        id: "duration_45",
        screen: "Sport setup",
        description: "45 min (nearest UI chip to 35 min persona fixture)",
        action: "tap_duration_chip",
        durationMinutes: 45,
      },
      {
        id: "build",
        screen: "Sport setup",
        description: "Build workout with hotel gym active",
        action: "tap_build_workout",
        expectRoute: "/sport-mode/recommendation",
        expectPhase: "review",
      },
      {
        id: "gym_assert",
        screen: "Recommendation",
        description: "Generation uses hotel gym equipment profile",
        action: "assert_gym_template",
        gymTemplate: "hotel_gym",
      },
      {
        id: "intent_parity",
        screen: "Recommendation",
        description: "Soccer speed/RSA intent in context",
        action: "assert_flow_intent_parity",
      },
    ],
  },
  {
    id: "deep_p10_drew_injury_sport",
    label: "P10 Drew — Sport day with knee + shoulder injury toggles → safe session",
    personaId: "P10",
    flow: "sport_day",
    testPriority: "P0",
    userStory:
      "User with knee and shoulder concerns selects soccer + speed in sport mode with injury status set.",
    expectedUserOutcome:
      "Usable session with contraindicated exercises filtered; no joint-stress violations.",
    steps: [
      { id: "home", screen: "Home", description: "Home", action: "assert_on_screen", expectRoute: "/" },
      {
        id: "sport_day",
        screen: "Home",
        description: "Sport one day",
        action: "tap_home_card",
        homeCard: "sport_day",
        expectRoute: "/sport-mode?scope=day",
      },
      {
        id: "sport_soccer",
        screen: "Sport setup",
        description: "Select soccer",
        action: "tap_sport",
        sportSlug: "soccer",
      },
      {
        id: "sub_speed",
        screen: "Sport setup",
        description: "Speed sub-focus",
        action: "toggle_subfocus",
        sportSlug: "soccer",
        subFocusSlug: "speed",
      },
      {
        id: "injury_status",
        screen: "Sport setup — injury section",
        description: "User sets injury status (not No Concerns) and selects Knee + Shoulder",
        action: "set_injury_status",
        injuryStatus: "Managing",
        injuryTypes: ["Knee", "Shoulder"],
        userExpectation: "Injury filters flow into generation constraints",
      },
      {
        id: "build",
        screen: "Sport setup",
        description: "Build workout",
        action: "tap_build_workout",
        expectRoute: "/sport-mode/recommendation",
        expectPhase: "review",
      },
      {
        id: "intent_parity",
        screen: "Recommendation",
        description: "Injuries + sport intent in generation path",
        action: "assert_flow_intent_parity",
      },
    ],
  },
];

export function getDeepScenarioById(id: string) {
  return DEEP_USER_FLOW_SCENARIOS.find((s) => s.id === id);
}
