/**
 * Minimal in-memory exercise dataset for testing the daily workout generator.
 * ~40 exercises spanning squat/hinge/push/pull/core/carry + conditioning + mobility.
 */

import type { Exercise } from "./types";

export const STUB_EXERCISES: Exercise[] = [
  // --- Squat ---
  {
    id: "goblet_squat",
    name: "Goblet Squat",
    movement_pattern: "squat",
    muscle_groups: ["legs", "core"],
    modality: "strength",
    equipment_required: ["dumbbells"],
    difficulty: 2,
    time_cost: "low",
    tags: {
      goal_tags: ["strength", "hypertrophy"],
      energy_fit: ["low", "medium", "high"],
      joint_stress: ["knee_flexion"],
      contraindications: ["knee_pain"],
      stimulus: ["eccentric"],
      attribute_tags: ["squat", "full_body"],
    },
    primary_movement_family: "lower_body",
    exercise_role: "main_compound",
    movement_patterns: ["squat"],
    aliases: ["goblet squat"],
    swap_candidates: ["barbell_back_squat", "front_squat", "leg_press", "bulgarian_split_squat"],
    stability_demand: "low",
    impact_level: "low",
  },
  {
    id: "barbell_back_squat",
    name: "Barbell Back Squat",
    movement_pattern: "squat",
    muscle_groups: ["legs", "core"],
    modality: "strength",
    equipment_required: ["barbell", "squat_rack"],
    difficulty: 3,
    time_cost: "high",
    tags: {
      goal_tags: ["strength", "power"],
      energy_fit: ["medium", "high"],
      joint_stress: ["knee_flexion", "lumbar_shear"],
      contraindications: ["knee_pain", "low_back_sensitive"],
      stimulus: ["eccentric"],
      attribute_tags: ["squat", "full_body"],
    },
    primary_movement_family: "lower_body",
    exercise_role: "main_compound",
    movement_patterns: ["squat"],
    fatigue_regions: ["quads", "glutes"],
    aliases: ["back squat", "squat"],
    swap_candidates: ["front_squat", "goblet_squat", "leg_press", "bulgarian_split_squat"],
    stability_demand: "low",
    impact_level: "low",
  },
  {
    id: "split_squat",
    name: "Rear-Foot Elevated Split Squat",
    movement_pattern: "squat",
    muscle_groups: ["legs"],
    modality: "strength",
    equipment_required: ["bench", "dumbbells"],
    difficulty: 3,
    time_cost: "medium",
    tags: {
      goal_tags: ["strength", "hypertrophy"],
      energy_fit: ["medium", "high"],
      joint_stress: ["knee_flexion"],
      contraindications: ["knee_pain"],
      stimulus: ["eccentric"],
      attribute_tags: ["squat", "full_body"],
    },
    primary_movement_family: "lower_body",
    exercise_role: "accessory",
    movement_patterns: ["lunge"],
    unilateral: true,
    stability_demand: "medium",
    impact_level: "low",
  },
  {
    id: "leg_press",
    name: "Leg Press",
    movement_pattern: "squat",
    muscle_groups: ["legs"],
    modality: "hypertrophy",
    equipment_required: ["leg_press"],
    difficulty: 1,
    time_cost: "medium",
    tags: {
      goal_tags: ["hypertrophy", "strength"],
      energy_fit: ["low", "medium", "high"],
      joint_stress: ["knee_flexion"],
      contraindications: ["knee_pain", "low_back_sensitive"],
      stimulus: ["eccentric"],
      attribute_tags: ["squat", "full_body"],
    },
  },
  {
    id: "step_up",
    name: "Step-up",
    movement_pattern: "squat",
    muscle_groups: ["legs"],
    modality: "strength",
    equipment_required: ["bench"],
    difficulty: 2,
    time_cost: "low",
    tags: {
      goal_tags: ["strength", "athleticism"],
      energy_fit: ["low", "medium", "high"],
      joint_stress: ["knee_flexion"],
      contraindications: ["knee_pain"],
      stimulus: ["eccentric"],
      attribute_tags: ["squat", "full_body"],
    },
  },
  // --- Hinge ---
  {
    id: "rdl_dumbbell",
    name: "Dumbbell Romanian Deadlift",
    movement_pattern: "hinge",
    muscle_groups: ["legs"],
    modality: "strength",
    equipment_required: ["dumbbells"],
    difficulty: 2,
    time_cost: "low",
    tags: {
      goal_tags: ["strength", "hypertrophy"],
      energy_fit: ["low", "medium", "high"],
      joint_stress: ["lumbar_shear"],
      contraindications: ["low_back_sensitive"],
      stimulus: ["eccentric", "scapular_control"],
      attribute_tags: ["deadlift_hinge", "full_body"],
    },
    primary_movement_family: "lower_body",
    pairing_category: "posterior_chain",
    fatigue_regions: ["hamstrings", "glutes"],
  },
  {
    id: "barbell_deadlift",
    name: "Barbell Deadlift",
    movement_pattern: "hinge",
    muscle_groups: ["legs", "core"],
    modality: "strength",
    equipment_required: ["barbell"],
    difficulty: 4,
    time_cost: "high",
    tags: {
      goal_tags: ["strength", "power"],
      energy_fit: ["medium", "high"],
      joint_stress: ["lumbar_shear"],
      contraindications: ["low_back_sensitive"],
      stimulus: ["eccentric", "grip"],
      attribute_tags: ["deadlift_hinge", "full_body"],
    },
    primary_movement_family: "lower_body",
    exercise_role: "main_compound",
    movement_patterns: ["hinge"],
    pairing_category: "posterior_chain",
    fatigue_regions: ["hamstrings", "glutes", "grip"],
    aliases: ["conventional deadlift", "DL"],
    swap_candidates: ["barbell_rdl", "trap_bar_deadlift", "hip_thrust"],
    grip_demand: "high",
    impact_level: "low",
  },
  {
    id: "hip_thrust",
    name: "Hip Thrust",
    movement_pattern: "hinge",
    muscle_groups: ["legs"],
    modality: "hypertrophy",
    equipment_required: ["barbell", "bench"],
    difficulty: 2,
    time_cost: "medium",
    tags: {
      goal_tags: ["hypertrophy", "strength"],
      energy_fit: ["low", "medium", "high"],
      joint_stress: [],
      contraindications: ["low_back_sensitive"],
      stimulus: ["eccentric"],
      attribute_tags: ["deadlift_hinge", "full_body"],
    },
    primary_movement_family: "lower_body",
    exercise_role: "accessory",
    movement_patterns: ["hinge"],
    pairing_category: "glutes",
    fatigue_regions: ["glutes"],
  },
  {
    id: "kb_swing",
    name: "Kettlebell Swing",
    movement_pattern: "hinge",
    muscle_groups: ["legs", "core", "glutes", "hamstrings"],
    modality: "conditioning",
    equipment_required: ["kettlebells"],
    difficulty: 2,
    time_cost: "medium",
    tags: {
      goal_tags: ["power", "endurance", "athleticism"],
      energy_fit: ["medium", "high"],
      joint_stress: ["lumbar_shear"],
      contraindications: ["low_back_sensitive"],
      stimulus: ["plyometric", "anaerobic"],
      attribute_tags: ["intervals_hiit"],
    },
    primary_movement_family: "full_body",
  },
  // --- Push ---
  {
    id: "bench_press_barbell",
    name: "Barbell Bench Press",
    movement_pattern: "push",
    muscle_groups: ["push"],
    modality: "strength",
    equipment_required: ["barbell", "bench", "squat_rack"],
    difficulty: 3,
    time_cost: "high",
    tags: {
      goal_tags: ["strength", "hypertrophy"],
      energy_fit: ["medium", "high"],
      joint_stress: ["shoulder_extension"],
      contraindications: ["rotator_cuff_irritation", "shoulder_overhead"],
      stimulus: ["eccentric"],
      attribute_tags: ["bench_press", "full_body"],
    },
    primary_movement_family: "upper_push",
    exercise_role: "main_compound",
    movement_patterns: ["horizontal_push"],
    pairing_category: "chest",
    fatigue_regions: ["pecs", "triceps"],
    aliases: ["bench", "BP", "barbell bench"],
    swap_candidates: ["db_bench", "incline_db_press", "push_up", "dips"],
    grip_demand: "medium",
    impact_level: "low",
  },
  {
    id: "db_bench",
    name: "Dumbbell Bench Press",
    movement_pattern: "push",
    muscle_groups: ["push"],
    modality: "hypertrophy",
    equipment_required: ["dumbbells", "bench"],
    difficulty: 2,
    time_cost: "medium",
    tags: {
      goal_tags: ["hypertrophy", "strength"],
      energy_fit: ["low", "medium", "high"],
      joint_stress: ["shoulder_extension"],
      contraindications: ["rotator_cuff_irritation"],
      stimulus: ["eccentric", "scapular_control"],
      attribute_tags: ["bench_press", "full_body"],
    },
    primary_movement_family: "upper_push",
    exercise_role: "accessory",
    movement_patterns: ["horizontal_push"],
    pairing_category: "chest",
  },
  {
    id: "oh_press",
    name: "Standing Overhead Press",
    movement_pattern: "push",
    muscle_groups: ["push", "core"],
    modality: "strength",
    equipment_required: ["barbell"],
    difficulty: 3,
    time_cost: "medium",
    tags: {
      goal_tags: ["strength", "power"],
      energy_fit: ["medium", "high"],
      joint_stress: ["shoulder_overhead"],
      contraindications: ["rotator_cuff_irritation", "low_back_sensitive"],
      stimulus: ["eccentric"],
      attribute_tags: ["overhead_press", "full_body"],
    },
    primary_movement_family: "upper_push",
    exercise_role: "main_compound",
    movement_patterns: ["vertical_push"],
    pairing_category: "shoulders",
  },
  {
    id: "db_shoulder_press",
    name: "Dumbbell Shoulder Press",
    movement_pattern: "push",
    muscle_groups: ["push"],
    modality: "hypertrophy",
    equipment_required: ["dumbbells"],
    difficulty: 2,
    time_cost: "medium",
    tags: {
      goal_tags: ["hypertrophy", "strength"],
      energy_fit: ["low", "medium", "high"],
      joint_stress: ["shoulder_overhead"],
      contraindications: ["rotator_cuff_irritation"],
      stimulus: ["eccentric"],
      attribute_tags: ["overhead_press", "full_body"],
    },
  },
  {
    id: "push_up",
    name: "Push-up",
    movement_pattern: "push",
    muscle_groups: ["push", "core"],
    modality: "strength",
    equipment_required: ["bodyweight"],
    difficulty: 1,
    time_cost: "low",
    tags: {
      goal_tags: ["strength", "calisthenics"],
      energy_fit: ["low", "medium", "high"],
      joint_stress: ["shoulder_extension"],
      stimulus: ["eccentric"],
      attribute_tags: ["bench_press", "full_body"],
    },
  },
  {
    id: "dips",
    name: "Dips",
    movement_pattern: "push",
    muscle_groups: ["push"],
    modality: "strength",
    equipment_required: ["bodyweight"],
    difficulty: 3,
    time_cost: "low",
    tags: {
      goal_tags: ["strength", "calisthenics"],
      energy_fit: ["medium", "high"],
      joint_stress: ["shoulder_extension"],
      contraindications: ["rotator_cuff_irritation"],
      stimulus: ["eccentric"],
      attribute_tags: ["bench_press", "full_body"],
    },
  },
  // --- Pull ---
  {
    id: "pullup",
    name: "Pull-up / Assisted Pull-up",
    movement_pattern: "pull",
    muscle_groups: ["pull"],
    modality: "strength",
    equipment_required: ["pullup_bar"],
    difficulty: 3,
    time_cost: "low",
    tags: {
      goal_tags: ["strength", "calisthenics"],
      energy_fit: ["medium", "high"],
      joint_stress: ["shoulder_extension", "grip_hanging"],
      contraindications: ["rotator_cuff_irritation"],
      stimulus: ["grip", "scapular_control"],
      attribute_tags: ["pull", "full_body"],
    },
    primary_movement_family: "upper_pull",
    exercise_role: "main_compound",
    movement_patterns: ["vertical_pull"],
    pairing_category: "grip",
    fatigue_regions: ["lats", "grip"],
  },
  {
    id: "lat_pulldown",
    name: "Lat Pulldown",
    movement_pattern: "pull",
    muscle_groups: ["pull"],
    modality: "hypertrophy",
    equipment_required: ["cable_machine", "lat_pulldown"],
    difficulty: 1,
    time_cost: "medium",
    tags: {
      goal_tags: ["hypertrophy", "strength"],
      energy_fit: ["low", "medium", "high"],
      joint_stress: ["shoulder_extension"],
      contraindications: ["rotator_cuff_irritation"],
      stimulus: ["scapular_control"],
      attribute_tags: ["pull", "full_body"],
    },
    primary_movement_family: "upper_pull",
    exercise_role: "accessory",
    movement_patterns: ["vertical_pull"],
    pairing_category: "lats",
  },
  {
    id: "db_row",
    name: "Single-Arm Dumbbell Row",
    movement_pattern: "pull",
    muscle_groups: ["pull", "core"],
    modality: "strength",
    equipment_required: ["dumbbells", "bench"],
    difficulty: 2,
    time_cost: "low",
    tags: {
      goal_tags: ["strength", "hypertrophy"],
      energy_fit: ["low", "medium", "high"],
      joint_stress: [],
      contraindications: ["low_back_sensitive"],
      stimulus: ["trunk_anti_rotation", "scapular_control"],
      attribute_tags: ["pull", "full_body"],
    },
  },
  {
    id: "cable_row",
    name: "Cable Seated Row",
    movement_pattern: "pull",
    muscle_groups: ["pull"],
    modality: "hypertrophy",
    equipment_required: ["cable_machine"],
    difficulty: 1,
    time_cost: "low",
    tags: {
      goal_tags: ["hypertrophy", "strength"],
      energy_fit: ["low", "medium", "high"],
      joint_stress: [],
      stimulus: ["scapular_control"],
      attribute_tags: ["pull", "full_body"],
    },
  },
  {
    id: "face_pull",
    name: "Cable Face Pull",
    movement_pattern: "pull",
    muscle_groups: ["pull"],
    modality: "mobility",
    equipment_required: ["cable_machine"],
    difficulty: 1,
    time_cost: "low",
    tags: {
      goal_tags: ["mobility", "recovery"],
      energy_fit: ["low", "medium", "high"],
      joint_stress: [],
      stimulus: ["scapular_control"],
    },
  },
  {
    id: "band_pullapart",
    name: "Band Pull-Apart",
    movement_pattern: "pull",
    muscle_groups: ["pull"],
    modality: "mobility",
    equipment_required: ["bands"],
    difficulty: 1,
    time_cost: "low",
    tags: {
      goal_tags: ["mobility", "recovery"],
      energy_fit: ["low", "medium", "high"],
      joint_stress: [],
      stimulus: ["scapular_control"],
    },
  },
  // --- Core ---
  {
    id: "plank",
    name: "Plank Hold",
    movement_pattern: "rotate",
    muscle_groups: ["core"],
    modality: "strength",
    equipment_required: ["bodyweight"],
    difficulty: 1,
    time_cost: "low",
    tags: {
      goal_tags: ["strength", "athleticism"],
      energy_fit: ["low", "medium", "high"],
      joint_stress: [],
      contraindications: ["low_back_sensitive"],
      stimulus: ["isometric", "anti_flexion"],
      attribute_tags: ["core", "full_body"],
    },
  },
  {
    id: "dead_bug",
    name: "Dead Bug",
    movement_pattern: "rotate",
    muscle_groups: ["core"],
    modality: "strength",
    equipment_required: ["bodyweight"],
    difficulty: 1,
    time_cost: "low",
    tags: {
      goal_tags: ["strength", "mobility", "recovery"],
      energy_fit: ["low", "medium", "high"],
      joint_stress: [],
      stimulus: ["anti_flexion", "trunk_anti_rotation"],
    },
  },
  {
    id: "pallof_hold",
    name: "Pallof Hold",
    movement_pattern: "rotate",
    muscle_groups: ["core"],
    modality: "strength",
    equipment_required: ["cable_machine", "bands"],
    difficulty: 2,
    time_cost: "low",
    tags: {
      goal_tags: ["strength", "athleticism"],
      energy_fit: ["low", "medium", "high"],
      joint_stress: [],
      stimulus: ["trunk_anti_rotation", "isometric"],
    },
  },
  {
    id: "bird_dog",
    name: "Bird Dog",
    movement_pattern: "rotate",
    muscle_groups: ["core"],
    modality: "mobility",
    equipment_required: ["bodyweight"],
    difficulty: 1,
    time_cost: "low",
    tags: {
      goal_tags: ["mobility", "recovery"],
      energy_fit: ["low", "medium", "high"],
      joint_stress: [],
      stimulus: ["anti_flexion"],
    },
  },
  // --- Carry ---
  {
    id: "farmer_carry",
    name: "Farmer Carry",
    movement_pattern: "carry",
    muscle_groups: ["core", "legs"],
    modality: "strength",
    equipment_required: ["dumbbells", "kettlebells"],
    difficulty: 1,
    time_cost: "low",
    tags: {
      goal_tags: ["strength", "endurance"],
      energy_fit: ["low", "medium", "high"],
      joint_stress: [],
      stimulus: ["grip"],
    },
  },
  {
    id: "suitcase_carry",
    name: "Suitcase Carry",
    movement_pattern: "carry",
    muscle_groups: ["core"],
    modality: "strength",
    equipment_required: ["dumbbells", "kettlebells"],
    difficulty: 2,
    time_cost: "low",
    tags: {
      goal_tags: ["strength", "athleticism"],
      energy_fit: ["low", "medium", "high"],
      joint_stress: [],
      stimulus: ["trunk_anti_rotation"],
    },
  },
  // --- Conditioning ---
  {
    id: "zone2_bike",
    name: "Zone 2 Bike",
    movement_pattern: "locomotion",
    muscle_groups: ["legs", "quads", "glutes"],
    modality: "conditioning",
    equipment_required: ["assault_bike"],
    difficulty: 1,
    time_cost: "high",
    estimated_minutes: 10,
    tags: {
      goal_tags: ["endurance"],
      energy_fit: ["low", "medium", "high"],
      joint_stress: ["knee_flexion"],
      contraindications: ["knee_pain"],
      stimulus: ["aerobic_zone2"],
      attribute_tags: ["zone2_aerobic_base"],
    },
    primary_movement_family: "lower_body",
  },
  {
    id: "zone2_treadmill",
    name: "Zone 2 Treadmill",
    movement_pattern: "locomotion",
    muscle_groups: ["legs", "quads", "glutes", "calves"],
    modality: "conditioning",
    equipment_required: ["treadmill"],
    difficulty: 1,
    time_cost: "high",
    estimated_minutes: 10,
    tags: {
      goal_tags: ["endurance"],
      energy_fit: ["low", "medium", "high"],
      joint_stress: ["knee_flexion"],
      contraindications: ["knee_pain"],
      stimulus: ["aerobic_zone2"],
      attribute_tags: ["zone2_aerobic_base"],
    },
    primary_movement_family: "lower_body",
  },
  {
    id: "rower",
    name: "Rower",
    movement_pattern: "locomotion",
    muscle_groups: ["legs", "pull", "core", "lats", "quads", "glutes"],
    modality: "conditioning",
    equipment_required: ["rower"],
    difficulty: 2,
    time_cost: "high",
    estimated_minutes: 10,
    tags: {
      goal_tags: ["endurance"],
      energy_fit: ["medium", "high"],
      joint_stress: [],
      stimulus: ["aerobic_zone2", "anaerobic"],
      attribute_tags: ["zone2_aerobic_base", "threshold_tempo", "intervals_hiit"],
    },
    primary_movement_family: "full_body",
  },
  {
    id: "ski_erg",
    name: "Ski Erg",
    movement_pattern: "locomotion",
    muscle_groups: ["legs", "pull", "core", "lats", "quads"],
    modality: "conditioning",
    equipment_required: ["ski_erg"],
    difficulty: 2,
    time_cost: "high",
    estimated_minutes: 10,
    tags: {
      goal_tags: ["endurance"],
      energy_fit: ["medium", "high"],
      joint_stress: [],
      stimulus: ["aerobic_zone2", "anaerobic"],
      attribute_tags: ["zone2_aerobic_base", "threshold_tempo", "intervals_hiit"],
    },
    primary_movement_family: "full_body",
  },
  {
    id: "walking_lunge",
    name: "Walking Lunge",
    movement_pattern: "locomotion",
    muscle_groups: ["legs", "quads", "glutes"],
    modality: "conditioning",
    equipment_required: ["bodyweight", "dumbbells"],
    difficulty: 2,
    time_cost: "medium",
    tags: {
      goal_tags: ["endurance", "athleticism"],
      energy_fit: ["medium", "high"],
      joint_stress: ["knee_flexion"],
      contraindications: ["knee_pain"],
      stimulus: ["eccentric"],
      attribute_tags: ["hills", "intervals_hiit"],
    },
    primary_movement_family: "lower_body",
  },

  // --- Hills / uphill repeats (intent: hills) ---
  {
    id: "treadmill_incline_walk",
    name: "Incline Treadmill Walk",
    movement_pattern: "locomotion",
    muscle_groups: ["legs", "quads", "glutes", "calves"],
    modality: "conditioning",
    equipment_required: ["treadmill"],
    difficulty: 1,
    time_cost: "high",
    estimated_minutes: 10,
    tags: {
      goal_tags: ["endurance"],
      energy_fit: ["medium", "high"],
      joint_stress: ["knee_flexion"],
      contraindications: ["knee_pain"],
      stimulus: ["aerobic_zone2"],
      attribute_tags: ["zone2_aerobic_base", "hills"],
    },
    primary_movement_family: "lower_body",
  },
  {
    id: "stair_climber_repeats",
    name: "Stair Climber Repeats",
    movement_pattern: "locomotion",
    muscle_groups: ["legs", "quads", "glutes", "calves"],
    modality: "conditioning",
    equipment_required: ["stair_climber"],
    difficulty: 2,
    time_cost: "high",
    estimated_minutes: 10,
    tags: {
      goal_tags: ["endurance"],
      energy_fit: ["medium", "high"],
      joint_stress: ["knee_flexion"],
      contraindications: ["knee_pain"],
      stimulus: ["anaerobic"],
      attribute_tags: ["hills", "intervals_hiit"],
    },
    primary_movement_family: "lower_body",
  },
  {
    id: "sled_push",
    name: "Sled Push",
    movement_pattern: "carry",
    muscle_groups: ["legs", "quads", "glutes", "calves"],
    modality: "conditioning",
    equipment_required: ["sled"],
    difficulty: 2,
    time_cost: "medium",
    estimated_minutes: 10,
    tags: {
      goal_tags: ["endurance"],
      energy_fit: ["medium", "high"],
      joint_stress: [],
      stimulus: ["anaerobic"],
      attribute_tags: ["hills", "intervals_hiit"],
    },
    primary_movement_family: "lower_body",
  },
  // --- Mobility / warmup / cooldown ---
  {
    id: "cat_camel",
    name: "Cat Cow",
    movement_pattern: "rotate",
    muscle_groups: ["core"],
    modality: "mobility",
    equipment_required: ["bodyweight"],
    difficulty: 1,
    time_cost: "low",
    tags: {
      goal_tags: ["mobility", "recovery"],
      energy_fit: ["low", "medium", "high"],
      joint_stress: [],
      stimulus: [],
    },
    exercise_role: "mobility",
    mobility_targets: ["thoracic_spine", "lumbar"],
    stretch_targets: ["low_back"],
    warmup_relevance: "high",
    cooldown_relevance: "high",
  },
  {
    id: "t_spine_rotation",
    name: "Quadruped T-Spine Rotation",
    movement_pattern: "rotate",
    muscle_groups: ["core"],
    modality: "mobility",
    equipment_required: ["bodyweight"],
    difficulty: 1,
    time_cost: "low",
    tags: {
      goal_tags: ["mobility", "recovery"],
      energy_fit: ["low", "medium", "high"],
      joint_stress: [],
      stimulus: [],
    },
    exercise_role: "mobility",
    mobility_targets: ["thoracic_spine"],
    stretch_targets: ["thoracic_spine"],
    warmup_relevance: "high",
    cooldown_relevance: "medium",
  },
  {
    id: "hip_90_90",
    name: "90/90 Hip Switch",
    movement_pattern: "rotate",
    muscle_groups: ["legs", "core"],
    modality: "mobility",
    equipment_required: ["bodyweight"],
    difficulty: 1,
    time_cost: "low",
    tags: {
      goal_tags: ["mobility", "recovery"],
      energy_fit: ["low", "medium", "high"],
      joint_stress: [],
      stimulus: [],
    },
    exercise_role: "mobility",
    mobility_targets: ["hip_internal_rotation", "hip_external_rotation"],
    stretch_targets: ["glutes", "hip_flexors"],
    warmup_relevance: "high",
    cooldown_relevance: "high",
  },
  {
    id: "worlds_greatest_stretch",
    name: "World's Greatest Stretch",
    movement_pattern: "locomotion",
    muscle_groups: ["legs", "core"],
    modality: "mobility",
    equipment_required: ["bodyweight"],
    difficulty: 2,
    time_cost: "low",
    tags: {
      goal_tags: ["mobility", "recovery"],
      energy_fit: ["low", "medium", "high"],
      joint_stress: [],
      stimulus: [],
    },
    warmup_relevance: "high",
    cooldown_relevance: "medium",
    aliases: ["WGS"],
    stretch_targets: ["hip_flexors", "hamstrings"],
  },
  {
    id: "standing_hamstring_stretch",
    name: "Standing Hamstring Stretch",
    movement_pattern: "rotate",
    muscle_groups: ["legs"],
    modality: "mobility",
    equipment_required: ["bodyweight"],
    difficulty: 1,
    time_cost: "low",
    tags: { goal_tags: ["mobility", "recovery"], energy_fit: ["low", "medium", "high"], joint_stress: [], stimulus: [] },
    exercise_role: "stretch",
    stretch_targets: ["hamstrings"],
    cooldown_relevance: "high",
  },
  {
    id: "lat_stretch_kneeling",
    name: "Kneeling Lat Stretch",
    movement_pattern: "rotate",
    muscle_groups: ["pull"],
    modality: "mobility",
    equipment_required: ["bodyweight"],
    difficulty: 1,
    time_cost: "low",
    tags: { goal_tags: ["mobility", "recovery"], energy_fit: ["low", "medium", "high"], joint_stress: [], stimulus: [] },
    exercise_role: "stretch",
    stretch_targets: ["lats"],
    cooldown_relevance: "high",
  },
  {
    id: "arm_circles",
    name: "Arm Circles",
    movement_pattern: "rotate",
    muscle_groups: ["push"],
    modality: "mobility",
    equipment_required: ["bodyweight"],
    difficulty: 1,
    time_cost: "low",
    tags: { goal_tags: ["mobility", "recovery"], energy_fit: ["low", "medium", "high"], joint_stress: [], stimulus: [] },
    exercise_role: "mobility",
    mobility_targets: ["shoulders"],
    warmup_relevance: "high",
  },
  {
    id: "breathing_cooldown",
    name: "Diaphragmatic Breathing",
    movement_pattern: "rotate",
    muscle_groups: ["core"],
    modality: "recovery",
    equipment_required: ["bodyweight"],
    difficulty: 1,
    time_cost: "low",
    tags: {
      goal_tags: ["recovery", "mobility"],
      energy_fit: ["low", "medium", "high"],
      joint_stress: [],
      stimulus: [],
    },
    exercise_role: "breathing",
    warmup_relevance: "low",
    cooldown_relevance: "high",
  },
  {
    id: "trap_bar_deadlift",
    name: "Trap Bar Deadlift",
    movement_pattern: "hinge",
    muscle_groups: ["legs", "core"],
    modality: "strength",
    equipment_required: ["trap_bar"],
    difficulty: 3,
    time_cost: "medium",
    tags: {
      goal_tags: ["strength", "power"],
      energy_fit: ["medium", "high"],
      joint_stress: ["lumbar_shear"],
      contraindications: ["low_back_sensitive"],
      stimulus: ["eccentric"],
    },
  },
  {
    id: "incline_db_press",
    name: "Incline Dumbbell Press",
    movement_pattern: "push",
    muscle_groups: ["push"],
    modality: "hypertrophy",
    equipment_required: ["dumbbells", "bench"],
    difficulty: 2,
    time_cost: "medium",
    tags: {
      goal_tags: ["hypertrophy", "strength"],
      energy_fit: ["low", "medium", "high"],
      joint_stress: ["shoulder_extension"],
      stimulus: ["eccentric"],
    },
    primary_movement_family: "upper_push",
    pairing_category: "chest",
    fatigue_regions: ["pecs", "triceps"],
  },
  {
    id: "trx_row",
    name: "TRX Row",
    movement_pattern: "pull",
    muscle_groups: ["pull", "core"],
    modality: "strength",
    equipment_required: ["trx"],
    difficulty: 2,
    time_cost: "low",
    tags: {
      goal_tags: ["strength", "calisthenics"],
      energy_fit: ["low", "medium", "high"],
      joint_stress: [],
      stimulus: ["scapular_control"],
    },
    primary_movement_family: "upper_pull",
    pairing_category: "back",
    fatigue_regions: ["lats"],
  },
  {
    id: "glute_bridge",
    name: "Glute Bridge",
    movement_pattern: "hinge",
    muscle_groups: ["legs"],
    modality: "strength",
    equipment_required: ["bodyweight"],
    difficulty: 1,
    time_cost: "low",
    tags: {
      goal_tags: ["strength", "hypertrophy", "recovery"],
      energy_fit: ["low", "medium", "high"],
      joint_stress: [],
      stimulus: ["eccentric"],
    },
    primary_movement_family: "lower_body",
    pairing_category: "posterior_chain",
    fatigue_regions: ["glutes"],
  },
  {
    id: "box_jump",
    name: "Box Jump",
    movement_pattern: "locomotion",
    muscle_groups: ["legs", "quads", "glutes"],
    modality: "conditioning",
    equipment_required: ["plyo_box"],
    difficulty: 2,
    time_cost: "low",
    tags: {
      goal_tags: ["power", "athleticism"],
      energy_fit: ["medium", "high"],
      joint_stress: ["knee_flexion"],
      contraindications: ["knee_pain"],
      stimulus: ["plyometric"],
      attribute_tags: ["intervals_hiit"],
    },
    primary_movement_family: "lower_body",
    impact_level: "high",
    stability_demand: "medium",
  },
  {
    id: "jump_rope",
    name: "Jump Rope",
    movement_pattern: "locomotion",
    muscle_groups: ["legs", "calves"],
    modality: "conditioning",
    equipment_required: ["bodyweight"],
    difficulty: 1,
    time_cost: "medium",
    tags: {
      goal_tags: ["endurance"],
      energy_fit: ["medium", "high"],
      joint_stress: ["knee_flexion"],
      stimulus: ["anaerobic", "plyometric"],
      attribute_tags: ["intervals_hiit"],
    },
    primary_movement_family: "lower_body",
    impact_level: "high",
  },
  {
    id: "burpee",
    name: "Burpee",
    movement_pattern: "locomotion",
    muscle_groups: ["legs", "core", "push", "quads", "glutes"],
    modality: "conditioning",
    equipment_required: ["bodyweight"],
    difficulty: 2,
    time_cost: "medium",
    tags: {
      goal_tags: ["endurance", "athleticism"],
      energy_fit: ["high"],
      joint_stress: ["knee_flexion"],
      stimulus: ["plyometric", "anaerobic"],
      attribute_tags: ["intervals_hiit"],
    },
    primary_movement_family: "full_body",
    impact_level: "high",
  },
  {
    id: "mountain_climbers",
    name: "Mountain Climbers",
    movement_pattern: "locomotion",
    muscle_groups: ["core", "legs", "push"],
    modality: "conditioning",
    equipment_required: ["bodyweight"],
    difficulty: 2,
    time_cost: "medium",
    tags: {
      goal_tags: ["endurance", "athleticism"],
      energy_fit: ["medium", "high"],
      joint_stress: [],
      stimulus: ["anaerobic"],
      attribute_tags: ["intervals_hiit"],
    },
    primary_movement_family: "core",
  },
];
