import path from "node:path";
import { defineConfig } from "vitest/config";

/**
 * Many `*.test.ts` files in this repo are legacy `npx tsx` harnesses (they call `main()` at load).
 * Vitest only runs suites that import from `vitest`. When you add a new Vitest suite, add its glob here.
 */
export default defineConfig({
  define: {
    // React Native / Expo modules reference this build-time global.
    __DEV__: false,
  },
  resolve: {
    alias: {
      // react-native ships Flow syntax that Rollup cannot parse in node tests.
      "react-native": path.resolve(__dirname, "test/stubs/react-native.ts"),
      // expo-secure-store pulls native runtime init; node tests only need the API shape.
      "expo-secure-store": path.resolve(__dirname, "test/stubs/expo-secure-store.ts"),
    },
  },
  test: {
    environment: "node",
    include: [
      "context/**/*.test.ts",
      "lib/db/**/*.test.ts",
      "lib/weekDaySessionFocus.test.ts",
      "lib/weekDaySessionFocus.bodyFocus.test.ts",
      "lib/weekDaySessionFocus.bodyFocusMode.test.ts",
      "lib/bodyFocusModeOverride.test.ts",
      "lib/workoutIntentSplit.test.ts",
      "lib/subFocusWeights.test.ts",
      "lib/goalRegistry.test.ts",
      "lib/recoveryGoalRanking.test.ts",
      "lib/preferencesConstants.conditioningSubFocusPolicy.test.ts",
      "lib/volumePreferenceCopy.test.ts",
      "lib/blockGoalDisplay.test.ts",
      "lib/appendGeneratedBlock.test.ts",
      "lib/generation/volumeRoleRanges.test.ts",
      "lib/preferenceConflictDetector.test.ts",
      "lib/daySessionFocusConflict.test.ts",
      "lib/sportModeOneDayValidation.test.ts",
      "lib/selectionCaps.parity.test.ts",
      "lib/sessionDraft.test.ts",
      "lib/newSessionFilters.test.ts",
      "lib/weekDayFocusRecommendation.test.ts",
      "lib/subGoalSplitCoverage.test.ts",
      "lib/trainToday.test.ts",
      "lib/weekProgress.test.ts",
      "lib/weekReviewCopy.test.ts",
      "lib/discardConfirmCopy.test.ts",
      "lib/activeWeekSnapshot.test.ts",
      "lib/dateUtils.test.ts",
      "lib/weekDesignation.test.ts",
      "lib/savedWeekUtils.test.ts",
      "lib/exerciseProgressions.swapPool.test.ts",
      "lib/generation/exerciseSubstitution.test.ts",
      "lib/generation/swapVariantDiversity.test.ts",
      "lib/dailyGeneratorAdapter.enduranceSecondary.test.ts",
      "lib/dailyGeneratorAdapter.rankedIntent.test.ts",
      "lib/dailyGeneratorAdapter.calisthenicsPrimaryGoal.test.ts",
      "lib/dailyGeneratorAdapter.goalSlugParity.test.ts",
      "lib/dailyGeneratorAdapter.bodyFocus.test.ts",
      "lib/splitMuscleMatching.test.ts",
      "lib/sessionBodyContract.test.ts",
      "lib/dailyGeneratorAdapter.goalMatchPreset.test.ts",
      "lib/energyLevelMapping.test.ts",
      "lib/gymEquipment.test.ts",
      "lib/gymProfileId.test.ts",
      "lib/pilotCatalog/trimCorePool.test.ts",
      "lib/buildAppTrainingHistory.test.ts",
      "lib/workoutCompletionLog.test.ts",
      "lib/sessionExerciseRedundancy.test.ts",
      "lib/exerciseDescriptionsCurated.test.ts",
      "lib/workoutUtils.exerciseDescription.test.ts",
      "lib/workoutUtils.prescription.test.ts",
      "lib/prefetchWorkoutGeneration.test.ts",
      "lib/staticExerciseCatalog.native.test.ts",
      "lib/tabBarHome.test.ts",
      "lib/generationPruningGateConfig.test.ts",
      "lib/saveNamedPlan.test.ts",
      "lib/useAnimatedEllipsis.test.ts",
      "lib/libraryCollections.test.ts",
      "lib/deferredDayBodySubFocus.test.ts",
      "lib/authRedirectAllowlist.test.ts",
      "scripts/fixCloudflarePagesAssets.test.ts",
      "data/sportSubFocus/speedAgilitySubFocusShared.test.ts",
      "data/sportSubFocus/verticalJumpSubFocusShared.test.ts",
      "data/sportSubFocus/subFocusIntentRegistry.test.ts",
      "data/sportSubFocus/enduranceSportPrepSecondaryGoal.test.ts",
      "data/sportSubFocus/enduranceJointStabilitySubFocus.test.ts",
      "logic/workoutGeneration/generationValidationGuardrail.test.ts",
      "logic/workoutGeneration/regenerationVariety.test.ts",
      "data/goalSubFocus/conditioningSubFocus.test.ts",
      "data/goalSubFocus/athleticGoalConsolidation.test.ts",
      "data/goalSubFocus/jointHealthSubFocus.test.ts",
      "data/jointHealthExerciseEnrichment.test.ts",
      "logic/workoutGeneration/jointHealthSession.test.ts",
      "logic/workoutGeneration/jointHealthActivationFamilies.test.ts",
      "logic/workoutGeneration/conditioningPoolBuilder.test.ts",
      "logic/workoutGeneration/enduranceConditioningFill.test.ts",
      "logic/workoutGeneration/defaultEngineCardioFilter.test.ts",
      "logic/workoutGeneration/accessorySupersetVariety.test.ts",
      "logic/workoutGeneration/sessionIntentCoverage.test.ts",
      "logic/workoutGeneration/intentSlotAllocator.test.ts",
      "logic/workoutGeneration/sessionVolumeTargets.test.ts",
      "logic/workoutGeneration/sessionVolumeFloors.test.ts",
      "logic/workoutGeneration/unifiedSlotProof.test.ts",
      "logic/workoutGeneration/roadRunningJointStabilityRepro.test.ts",
      "logic/workoutGeneration/surfingSportSubFocusDisplay.test.ts",
      "logic/workoutGeneration/cooldownWarmupExclusion.test.ts",
      "logic/workoutGeneration/goalDedicatedBlocks.test.ts",
      "logic/workoutGeneration/subFocusResilienceThreshold.test.ts",
      "logic/workoutGeneration/sportSubFocusSessionCoverage.test.ts",
      "logic/workoutGeneration/verticalJumpGeneration.test.ts",
      "logic/workoutGeneration/olympicTripleExtensionGeneration.test.ts",
      "logic/workoutGeneration/subGoalGenerationFidelity.test.ts",
      "logic/workoutGeneration/personaDeepLoopRepro.test.ts",
      "logic/workoutGeneration/personaFixtures.test.ts",
      "logic/workoutGeneration/sportSubGoalGenerationFidelity.test.ts",
      "logic/workoutGeneration/weightedAlignmentScoring.test.ts",
      "logic/workoutGeneration/blockSelectionEligibility.test.ts",
      "logic/workoutGeneration/blockCategoryBehavior.test.ts",
      "logic/workoutGeneration/blockCategoryGeneration.test.ts",
      "logic/workoutGeneration/supersetPairPreferenceBoost.test.ts",
      "logic/workoutGeneration/supersetIntentPreferenceScores.test.ts",
      "logic/workoutGeneration/bodyRecompConditioningPolicy.test.ts",
      "logic/workoutGeneration/secondaryGoalBlockLabeling.test.ts",
      "logic/workoutGeneration/sessionBlockPresentation.test.ts",
      "logic/workoutGeneration/blockIntentProfile.test.ts",
      "logic/workoutGeneration/sessionFeelProfile.test.ts",
      "logic/workoutIntelligence/goalQualityWeights.test.ts",
      "logic/workoutGeneration/sessionFeelPrescription.test.ts",
      "logic/workoutIntelligence/constraints/resolveWorkoutConstraints.intentConditioning.test.ts",
      "logic/workoutGeneration/workoutStylePolicy.test.ts",
      "lib/dailyGeneratorAdapter.workoutStyle.test.ts",
      "lib/exerciseMetadata/phase9DynamicPowerTagInference.test.ts",
      "logic/workoutIntelligence/constraints/resolveWorkoutConstraints.intentConditioning.test.ts",
      "logic/workoutGeneration/calisthenicsConditioningPolicy.test.ts",
      "logic/workoutGeneration/upperHypertrophySessionGate.test.ts",
      "logic/workoutGeneration/bodyFocusSubFocusFilter.test.ts",
      "logic/workoutGeneration/powerUpperBodyWeeklyDay.test.ts",
      "logic/workoutGeneration/gluteBridgeHipThrustRedundancy.test.ts",
      "logic/workoutGeneration/pruningGatePool.eligibilityMap.test.ts",
      "logic/workoutGeneration/hypertrophyAccessoryWallDrill.test.ts",
      "logic/workoutIntelligence/validation/workoutValidator.test.ts",
      "logic/workoutIntelligence/scoring/exerciseScoring.test.ts",
      "logic/workoutIntelligence/scoring/qualityResolution.test.ts",
      "logic/workoutIntelligence/weekly/phase12-weekly-planning.test.ts",
      "services/sportPrepPlanner/failurePaths.test.ts",
      "services/sportPrepPlanner/weekDaySlotAssignment.test.ts",
      "services/sportPrepPlanner/updatePlanDayDate.test.ts",
      "services/sportPrepPlanner/sportDesignatedDay.test.ts",
      "services/sportPrepPlanner/planWeekSportDays.test.ts",
    ],
    passWithNoTests: false,
  },
});
