import { defineConfig } from "vitest/config";

/**
 * Many `*.test.ts` files in this repo are legacy `npx tsx` harnesses (they call `main()` at load).
 * Vitest only runs suites that import from `vitest`. When you add a new Vitest suite, add its glob here.
 */
export default defineConfig({
  test: {
    environment: "node",
    include: [
      "context/**/*.test.ts",
      "lib/db/**/*.test.ts",
      "lib/weekDaySessionFocus.test.ts",
      "lib/workoutIntentSplit.test.ts",
      "lib/subFocusWeights.test.ts",
      "lib/preferencesConstants.conditioningSubFocusPolicy.test.ts",
      "lib/preferenceConflictDetector.test.ts",
      "lib/sportModeOneDayValidation.test.ts",
      "lib/exerciseProgressions.swapPool.test.ts",
      "lib/dailyGeneratorAdapter.enduranceSecondary.test.ts",
      "lib/dailyGeneratorAdapter.rankedIntent.test.ts",
      "lib/dailyGeneratorAdapter.calisthenicsPrimaryGoal.test.ts",
      "lib/dailyGeneratorAdapter.goalSlugParity.test.ts",
      "lib/dailyGeneratorAdapter.bodyFocus.test.ts",
      "lib/gymEquipment.test.ts",
      "lib/buildAppTrainingHistory.test.ts",
      "lib/exerciseDescriptionsCurated.test.ts",
      "lib/workoutUtils.exerciseDescription.test.ts",
      "data/sportSubFocus/speedAgilitySubFocusShared.test.ts",
      "data/sportSubFocus/enduranceSportPrepSecondaryGoal.test.ts",
      "data/sportSubFocus/enduranceJointStabilitySubFocus.test.ts",
      "logic/workoutGeneration/generationValidationGuardrail.test.ts",
      "logic/workoutGeneration/regenerationVariety.test.ts",
      "logic/workoutGeneration/accessorySupersetVariety.test.ts",
      "logic/workoutGeneration/sessionIntentCoverage.test.ts",
      "logic/workoutGeneration/intentSlotAllocator.test.ts",
      "logic/workoutGeneration/unifiedSlotProof.test.ts",
      "logic/workoutGeneration/roadRunningJointStabilityRepro.test.ts",
      "logic/workoutGeneration/surfingSportSubFocusDisplay.test.ts",
      "logic/workoutGeneration/cooldownWarmupExclusion.test.ts",
      "logic/workoutGeneration/goalDedicatedBlocks.test.ts",
      "logic/workoutGeneration/subFocusResilienceThreshold.test.ts",
      "logic/workoutGeneration/sportSubFocusSessionCoverage.test.ts",
      "logic/workoutGeneration/supersetPairPreferenceBoost.test.ts",
      "logic/workoutGeneration/supersetIntentPreferenceScores.test.ts",
      "logic/workoutGeneration/bodyRecompConditioningPolicy.test.ts",
      "logic/workoutGeneration/blockIntentProfile.test.ts",
      "logic/workoutGeneration/sessionFeelProfile.test.ts",
      "logic/workoutIntelligence/goalQualityWeights.test.ts",
      "logic/workoutGeneration/sessionFeelPrescription.test.ts",
      "logic/workoutIntelligence/constraints/resolveWorkoutConstraints.intentConditioning.test.ts",
      "logic/workoutGeneration/workoutStylePolicy.test.ts",
      "lib/dailyGeneratorAdapter.workoutStyle.test.ts",
      "lib/exerciseMetadata/phase9DynamicPowerTagInference.test.ts",
      "logic/workoutIntelligence/constraints/resolveWorkoutConstraints.intentConditioning.test.ts",
      "logic/workoutGeneration/calisthenicsConditioningPolicy.test.ts",
      "logic/workoutGeneration/upperHypertrophySessionGate.test.ts",
      "logic/workoutIntelligence/scoring/exerciseScoring.test.ts",
      "logic/workoutIntelligence/scoring/qualityResolution.test.ts",
      "logic/workoutIntelligence/weekly/phase12-weekly-planning.test.ts",
      "services/sportPrepPlanner/failurePaths.test.ts",
      "services/sportPrepPlanner/updatePlanDayDate.test.ts",
    ],
    passWithNoTests: false,
  },
});
